import os

# srcpath is the folder containing the game directory with source code (i.e. server, client and shared)
srcpath = '..'

# Paths to be searched by Python for modules containing the binding code
searchpaths = [
    os.path.normpath('game/client/python/modules/'),
    os.path.normpath('game/server/python/modules/'),
    os.path.normpath('game/shared/python/modules/'),
]

# Output folder name, used for creating filters by VPC (see srcpypp.genvpc)
autogenfoldername = 'autogenerated'

# Output paths for generated binding code (must use autogenfoldername)
client_path = os.path.normpath('game/client/python/modules/%s/' % (autogenfoldername))
server_path = os.path.normpath('game/server/python/modules/%s/' % (autogenfoldername))
shared_path = os.path.normpath('game/shared/python/modules/%s/' % (autogenfoldername))

# Branch (currently either "swarm" or "source2013")
branch = "source2013"
# Output paths for generated VPC file, to be included in the game VPC files
vpcserverpath = os.path.join(srcpath, 'game/server/server_pysource_autogen.vpc')
vpcclientpath = os.path.join(srcpath, 'game/client/client_pysource_autogen.vpc')

# The list of modules
# The parse code looks in the above paths
modules = [
    # Base
    ('srcbuiltins', 'SrcBuiltins'),
    ('_vmath', 'VMath'),
    
    # Game
    ('_animation', 'Animation'),
    ('_entities', 'Entities'),
    ('_entitiesmisc', 'EntitiesMisc'),
    ('_gameinterface', 'GameInterface'),
    ('_utils', 'Utils'),
    ('_physics', 'Physics'),
    ('_sound', 'Sound'),
    ('_particles', 'Particles'),

    # Misc
    ('steam', 'Steam'),
    ('_ndebugoverlay', 'NDebugOverlay'),
    ('vprof', 'VProf'),
]

