//=============================================================================//
// This file is automatically generated. CHANGES WILL BE LOST.
//=============================================================================//
#include "cbase.h"
#include "srcpy.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

using namespace boost::python;

// The init method is in one of the generated files declared
#ifdef _WIN32
extern "C" __declspec(dllexport) PyObject* PyInit__input();
extern "C" __declspec(dllexport) PyObject* PyInit__vgui();
extern "C" __declspec(dllexport) PyObject* PyInit__vguicontrols();
#else
extern "C"  PyObject* PyInit__input();
extern "C"  PyObject* PyInit__vgui();
extern "C"  PyObject* PyInit__vguicontrols();
#endif // _WIN32

// The append function
void AppendClientModules()
{
	APPEND_MODULE(_input)
	APPEND_MODULE(_vgui)
	APPEND_MODULE(_vguicontrols)
}
